#!/bin/bash

# Git Shell Coloring
RESTORE='\033[0m'    # Text Reset means no color change
RED='\033[00;31m'	 # Red color code
YELLOW='\033[00;33m' # yellow color code
BLUE='\033[00;34m'   # blue color code

FORBIDDEN=( 'import Input from' '../../js/Jetstream/Input' )
FOUND=''

for j in "${FORBIDDEN[@]}"
do
  for i in `git diff --cached --name-only`
  do

    # the trick is here...use `git show :file` to output what is staged
    # test it against each of the FORBIDDEN strings ($j)

    if echo `git show :$i` | grep -q "$j"; then

      FOUND+="${BLUE}$i ${RED}contains ${RESTORE}\"$j\"${RESTORE}\n"

    fi
  done
done

# if FOUND is not empty, REJECT the COMMIT
# PRINT the results (colorful-like)

if [[ ! -z $FOUND ]]; then
  printf "${YELLOW}COMMIT REJECTED\n"
  printf "$FOUND"
  exit 1
fi

# nothing found? let the commit happen
exit 0
