#!/bin/sh

echo "Skip pre-push hooks with --no-verify (not recommended).\n"

BRANCH=`git rev-parse --abbrev-ref HEAD`
if [ "$BRANCH" = "mains" ];
then
  echo "You are on branch $BRANCH. You must not push to main\n"
  exit 1
fi

if [ `date +%w` -ge 5 ] && [ "$BRANCH" = "develop" ];
then
  echo "Please, do not push code to develop before the weekend!\n"
  exit 1
fi
